### ISSUE TITLE
Change the SLD style

### ISSUE THREAD

**Issue by ebocher** [Universite-Gustave-Eiffel/NoiseCapture#131]
The SLD  style of the hexagons map must be changed to show the intensity of the measure.
I will do a proposal.

**Comment by nicolas-f** [comment]
What is the intensity of the measure ?

**Comment by ebocher** [comment]
From 0 to 100 db

**Comment by nicolas-f** [comment]
You are talking about changing the color ramp of the noise level ?

**Comment by ebocher** [comment]
yep we talk about intensity in cartography sorry ;-)

**Comment by ebocher** [comment]
There is a new style available on the geoserver side with the name  noise_style_proposal. It fixes #181

Previous style

![old_style](https://user-images.githubusercontent.com/1820572/29529274-4db5aef8-869f-11e7-9676-5c34482ba059.png)


New style

![new_style](https://user-images.githubusercontent.com/1820572/29529281-58f05638-869f-11e7-9edc-29adb969ab7e.png)

From 0 to 40 range of green values to express low db (quiet areas)
From 40 to 65 yellow to orange (less quiet areas)
From 65 to 80 red to black (high-noise areas )

Feel free to comment

**Comment by ebocher** [comment]
If you want to create a new style and a better one you can try http://eyetracking.upol.cz/color/

**Comment by gpetit** [comment]
Since we are trying to follow official or community endorsed color scheme, I think we can close this issue.
The possible color schemes are documented here https://noisemodelling.readthedocs.io/en/latest/Noise_Map_Color_Scheme.html
