### ISSUE TITLE
Test expanded low-frequency register with a set of smartphones and sonometers

### ISSUE THREAD

**Issue by toulemonde** [Universite-Gustave-Eiffel/NoiseCapture#256]
Hello, 
I am taking part in a CINOV-GIAc workgroup aiming to build a wide acoustical databse of human activities. NoiseCapture seems to be the best tool to help us make measurements when we don't carry our professional sonometers with us, while contributing to adding measurements to your database. 
Of course, we must begin by assessing the precision of our devices, compared to our class 1 sonometers. 
One noticeable difference between professional class 1 sonometers and an Android smartphone equiped with an external omnidirectional mike, NoiseCapture App and a serious calibration procedure, is the ability to measure sound levels below 1/3-octave 100 Hz. 
We have understood that you have set this limitation according to Android CDD "The device SHOULD exhibit approximately flat amplitude versus frequency characteristics: specifically, ±3 dB, from 100 Hz to 4000 Hz". However, we would like to assess whether some recent Android phones may offer a reasonably flat amplitude below these frequencies (16 Hz - 80 Hz). 
We propose that our companies carry out a set of tests (lab and/or real-life measurements) using a special version of NoiseCapture, that would allow us to compare low frequency measurements performed by our smartphones with the same measurements performed by class 1 sonometers. Would you be interested ? 
I look forward to hear from you. 
Thomas

**Comment by Picaut** [comment]
Dear Thomas
Thank you for this contribution. I contact you soon.
J. Picaut

**Comment by toulemonde** [comment]
Hello Judicaël,
Nous sommes toujours partants pour cette expérimentation. A ta disposition pour en discuter.
Thomas Toulemonde

**Comment by pierromond** [comment]
@Picaut
