### ISSUE TITLE
Update NoiseCapture description on PlayStore

### ISSUE THREAD

**Issue by nicolas-f** [Universite-Gustave-Eiffel/NoiseCapture#318]
Update NoiseCapture description on playstore with new screenshot of calibration and talk about innovative traffic calibration method.

**Comment by nicolas-f** [comment]
We should update the calibration web page also ? @pierromond @gpetit ?

**Comment by pierromond** [comment]
Yes ! Who opens a shared document?

**Comment by gpetit** [comment]
Yes you are right.
The shared doc is created. You should have received a notification

**Comment by nicolas-f** [comment]
In my opinion the document is ready, what do you think? @gpetit

**Comment by gpetit** [comment]
Thx. I will have a look

**Comment by pierromond** [comment]
Can we close this issue ?

**Comment by gpetit** [comment]
I guess so. The road traffic calibration has been documented : https://noise-planet.org/noisecapture_calibration.html
