### ISSUE TITLE
App & Website localization

### ISSUE THREAD

**Issue by jayrope** [Universite-Gustave-Eiffel/NoiseCapture#363]
I would like to help localize the Noise Capture App and the subsequent display of data on the map to German language. How can this be done?

**Comment by gpetit** [comment]
Hi @jayrope,

Thanks for your proposal. To translate, both NoiseCapture and the website, we are using the Transifex platform (which is free). The app and the website are divided in two separated projects

- NoiseCapture : https://www.transifex.com/LAE/noisecapture/dashboard/
- Website : https://www.transifex.com/LAE/noise-planet-website/dashboard/

In the NoiseCapture, there is already a German (de) translation started. So you will have to join the existing team.
In the website, there is no German translation. So you can ask to start it, and once validated by us, you should become the admin of this team

More informations can be found here : https://github.com/Ifsttar/NoiseCapture/wiki/10.-Contributing
