### ISSUE TITLE
Illegal track UUID error message when trying to upload measures

### ISSUE THREAD

**Issue by MatthieuQ** [Universite-Gustave-Eiffel/NoiseCapture#383]
Unable to send measurements.
An error containing the message illegal track UUID appears.

The screenshot shows the beginning of the error.
![Screenshot_20230523_135025_NoiseCapture](https://github.com/Universite-Gustave-Eiffel/NoiseCapture/assets/633645/9053d2fe-e852-4d4b-b25c-9ed2f9cb35d2)

**Comment by nicolas-f** [comment]
Hello,

Thanks for the report. There was a database issue since 17 may..

It should be up now, but there is some work to process records since this date.
