### ISSUE TITLE
17/07/2024 - Error in client

### ISSUE THREAD

**Issue by P-gK** [Universite-Gustave-Eiffel/NoiseCapture#401]
Dear Noiseplanet Team

Several of us have received an error message today during recordings transfer from the client to the server:
"failed to connect to onomap-gs.noise-planet.org"

Regards,
PG

**Comment by nicolas-f** [comment]
Hello,

Yes thank you for your feedback. Our data-center is currently facing connectivity issues and our team is working on it. Sorry for the inconveniences.

**Comment by nicolas-f** [comment]
Services are up and some measurements has been processed. Sorry for the delay
